services:
  orders:
    image: weshigbee/orders-sluggish:latest
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - "*.pyc"
            - "__pycache__/"
            - ".git/"
            - "uv.lock"
